// <auto-generated />
using System;
using KCFanClub.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KCFanClub.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240510220702_TweakDatesOnMatches")]
    partial class TweakDatesOnMatches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KCFanClub.Server.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Opponent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Match");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 5, 16, 0, 7, 2, 246, DateTimeKind.Local).AddTicks(7096),
                            Opponent = "Orlando Pirates",
                            Time = "hh:00 tt",
                            Venue = "Orlando Stadium"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 5, 18, 0, 7, 2, 246, DateTimeKind.Local).AddTicks(7166),
                            Opponent = "Golden Arrows",
                            Time = "hh:00 tt",
                            Venue = "Lamontville Stadium"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 5, 20, 0, 7, 2, 246, DateTimeKind.Local).AddTicks(7170),
                            Opponent = "Bloemfontein Celtics",
                            Time = "12:00 am",
                            Venue = "Bloemfontein Stadium"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 5, 22, 0, 7, 2, 246, DateTimeKind.Local).AddTicks(7232),
                            Opponent = "Mamelodi Sundowns",
                            Time = "hh:00 tt",
                            Venue = "HM Pitje Stadium"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 5, 26, 0, 7, 2, 246, DateTimeKind.Local).AddTicks(7236),
                            Opponent = "Moroka Swallows",
                            Time = "hh:00 tt",
                            Venue = "Moroka Stadium"
                        });
                });

            modelBuilder.Entity("KCFanClub.Server.Models.PlayerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PlayerProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
