// <auto-generated />
using KCFanClub.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KCFanClub.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240512222448_AddMorePlayers")]
    partial class AddMorePlayers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KCFanClub.Server.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Opponent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Match");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "2024/05/18",
                            Opponent = "Orlando Pirates",
                            Time = "12:00 am",
                            Venue = "Orlando Stadium"
                        },
                        new
                        {
                            Id = 2,
                            Date = "2024/05/20",
                            Opponent = "Golden Arrows",
                            Time = "12:00 am",
                            Venue = "Lamontville Stadium"
                        },
                        new
                        {
                            Id = 3,
                            Date = "2024/05/23",
                            Opponent = "Bloemfontein Celtics",
                            Time = "12:00 am",
                            Venue = "Bloemfontein Stadium"
                        },
                        new
                        {
                            Id = 4,
                            Date = "2024/05/27",
                            Opponent = "Mamelodi Sundowns",
                            Time = "12:00 am",
                            Venue = "HM Pitje Stadium"
                        },
                        new
                        {
                            Id = 5,
                            Date = "2024/06/01",
                            Opponent = "Moroka Swallows",
                            Time = "12:00 am",
                            Venue = "Moroka Stadium"
                        });
                });

            modelBuilder.Entity("KCFanClub.Server.Models.MatchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AwayScore")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HomeScore")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MatchResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayScore = "0",
                            AwayTeam = "Orlando Pirates",
                            HomeScore = "3",
                            HomeTeam = "Kaizer Chiefs"
                        },
                        new
                        {
                            Id = 2,
                            AwayScore = "2",
                            AwayTeam = "Kaizer Chiefs",
                            HomeScore = "1",
                            HomeTeam = "Polokwane City"
                        },
                        new
                        {
                            Id = 3,
                            AwayScore = "0",
                            AwayTeam = "TS Galaxy",
                            HomeScore = "1",
                            HomeTeam = "Kaizer Chiefs"
                        },
                        new
                        {
                            Id = 4,
                            AwayScore = "3",
                            AwayTeam = "AmaZulu",
                            HomeScore = "2",
                            HomeTeam = "Kaizer Chiefs"
                        },
                        new
                        {
                            Id = 5,
                            AwayScore = "0",
                            AwayTeam = "Kaizer Chiefs",
                            HomeScore = "3",
                            HomeTeam = "Cape Town City"
                        });
                });

            modelBuilder.Entity("KCFanClub.Server.Models.PlayerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PlayerProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium",
                            Name = "Itumeleng Khune",
                            Nationality = "South African",
                            Position = "Goalkeeper"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium",
                            Name = "Jasond González",
                            Nationality = "Colombian",
                            Position = "Forward"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium",
                            Name = "Ashley Du Preez",
                            Nationality = "South African",
                            Position = "Forward"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium",
                            Name = "Mfundo Vilakazi",
                            Nationality = "South African",
                            Position = "Midfielder"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium",
                            Name = "Edson Castillo",
                            Nationality = "Venezuelan",
                            Position = "Midfielder"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium",
                            Name = "Edmilson Dove",
                            Nationality = "Mozambique",
                            Position = "Defender"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium",
                            Name = "Thatayaone Ditlhokwe",
                            Nationality = "Botswana",
                            Position = "Defender"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium",
                            Name = "Njabulo Ngcobo",
                            Nationality = "South African",
                            Position = "Defender"
                        });
                });

            modelBuilder.Entity("KCFanClub.Server.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Test",
                            Username = "Test"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Sed ut perspiciatis unde omnis iste",
                            Username = "Test1"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Sed ut perspiciatis unde omnis iste",
                            Username = "John"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Sed ut perspiciatis unde omnis iste",
                            Username = "Jane"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
