// <auto-generated />
using KCFanClub.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KCFanClub.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240511114345_PopulatePlayerTable")]
    partial class PopulatePlayerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KCFanClub.Server.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Opponent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Match");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "2024/05/16",
                            Opponent = "Orlando Pirates",
                            Time = "01:00 pm",
                            Venue = "Orlando Stadium"
                        },
                        new
                        {
                            Id = 2,
                            Date = "2024/05/18",
                            Opponent = "Golden Arrows",
                            Time = "01:00 pm",
                            Venue = "Lamontville Stadium"
                        },
                        new
                        {
                            Id = 3,
                            Date = "2024/05/21",
                            Opponent = "Bloemfontein Celtics",
                            Time = "01:00 pm",
                            Venue = "Bloemfontein Stadium"
                        },
                        new
                        {
                            Id = 4,
                            Date = "2024/05/25",
                            Opponent = "Mamelodi Sundowns",
                            Time = "01:00 pm",
                            Venue = "HM Pitje Stadium"
                        },
                        new
                        {
                            Id = 5,
                            Date = "2024/05/30",
                            Opponent = "Moroka Swallows",
                            Time = "01:00 pm",
                            Venue = "Moroka Stadium"
                        });
                });

            modelBuilder.Entity("KCFanClub.Server.Models.PlayerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PlayerProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium",
                            Name = "Itumeleng Khune",
                            Nationality = "South African",
                            Position = "Goalkeeper"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium",
                            Name = "Jasond González",
                            Nationality = "Colombian",
                            Position = "Forward"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium",
                            Name = "Ashley Du Preez",
                            Nationality = "South African",
                            Position = "Forward"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium",
                            Name = "Mfundo Vilakazi",
                            Nationality = "South African",
                            Position = "Midfielder"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium",
                            Name = "Edson Castillo",
                            Nationality = "Venezuelan",
                            Position = "Midfielder"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
